name = "miku-tools"
type = "webpack"
account_id = ""
workers_dev = true

kv_namespaces = [
  { binding = "TOOLS_DATA", id = "", preview_id = "" }
]

[site]
bucket = "dist"
entry-point = "workers-site"

[build]
command = "npm install --legacy-peer-deps && npm run generate"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18.17.1"
NODE_ENV = "production"
NPM_VERSION = "9.6.7"

[vars]
ENVIRONMENT = "production"