name = "miku-tools"
type = "webpack"
account_id = ""
workers_dev = true

kv_namespaces = [
  { binding = "TOOLS_DATA", id = "", preview_id = "" }
]

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run generate"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18.17.1"